version: '3'
services:
  server:
    container_name: Kevlar
    entrypoint: yarn start
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3456:3456'
