name: CI

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
  prepare-environment:
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: Stop and remove containers, networks
        run: docker-compose down kevlar
      - name: Remove unused data
        run: docker-compose rm -f kevlar
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: docker-compose
        run: docker-compose up --build -d
