name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Stop existing Docker container
        run: |
          docker stop Kevlar
      - name: Build and run Docker Compose
        run: |
          docker-compose up --build -d
