name: CI

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
  prepare-environment:
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: Stop and remove containers, networks
        run: |
          if docker ps -a | grep Kevlar ; then
            docker rm -f Kevlar
          else
            echo "Container Kevlar does not exist"
          fi
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: docker-compose
        run: docker-compose up --build -d
